
<h3 class="title"><?php echo $this->__('Magento Spreadsheet') ?></h3>
<p><?php echo $this->__('This beautiful Magento spreadsheet holds data. Feel free to add your own data in any field and hit "save". Or add a key and hit "load" to populate it.') ?></p>

<table id="cata-spreadsheet-table" class="data-table">
    <?php for ($x = 0; $x <= 7; $x++): ?>
        <tr>
            <?php for ($y = 0; $y <= 7; $y++): ?>
                <td>
                    <input type="text" class="input-text" value="" />
                </td>
            <?php endfor ?>
        </tr>
    <?php endfor ?>
</table>

<form id="cata-spreadsheet-form" action="#">
    <div class="input-box">
        <input type="text" id="cata-spreadsheet-key" name="cata-spreadsheet-key" class="input-text required-entry" value="" />
    </div>
    <div class="buttons-set">
        <button id="cata-spreadsheet-save" type="button" class="button">
            <span>
                <span><?php echo $this->__('Save') ?></span>
            </span>
        </button>
        <button id="cata-spreadsheet-load" type="button" class="button">
            <span>
                <span><?php echo $this->__('Load') ?></span>
            </span>
        </button>
    </div>
</form>

<script>
    // jQuery wrapper
    (function ($) {
        // Remove the two dummy functions below, if you want to add a test harness
        var save_data = function (key, data) {
            console.log(key, data);
        };

        var load_data = function (key) {
            var testJSON = {
                'test-1': '[[1, 2],[],[0, 4, 0, 5, 8]]',
                'test-2': '[[],[1, 3, 4, 8],[9, 4, 0]]',
                'test-3': '[[],[1, 3, 4, 8],[9, 4, 0],[], [],[1, 3, 4, 8],[9, 4, 0],[0, 1]]'
            };

            return testJSON[key];
        };

        $(document).on('ready', function () {
            var $body = $('body'),
                $table = $body.find('#cata-spreadsheet-table'),
                $dataKey = $body.find('#cata-spreadsheet-key'),
                $saveBtn = $body.find('#cata-spreadsheet-save'),
                $loadBtn = $body.find('#cata-spreadsheet-load');

            $saveBtn.on('click', function () {
                var key = $dataKey.val();

                if ( !key ) {
                    alert('Error! You need to add a key if you want to save.');
                    return;
                }

                var data = cataSpreadsheet.extractData($table);

                if ( !cataSpreadsheet.isDataGood(data) ) {
                    alert('Error! Your table is obviously larger than 8 * 8.');
                    return;
                }

                var dataAsString = JSON.stringify(data);

                save_data(key, dataAsString);
            });

            $loadBtn.on('click', function () {
                var key = $dataKey.val();

                if ( !key ) {
                    alert('Error! You should add a key if you want to load something.');
                    return;
                }

                var dataAsString = load_data(key);

                if (!dataAsString) {
                    alert('Error! This key does not produce any data.');
                    return;
                }

                var data = JSON.parse(dataAsString);

                if ( !cataSpreadsheet.isDataGood(data) ) {
                    alert('Error! The array you are trying to insert is larger than 8 * 8.');
                    return;
                }

                cataSpreadsheet.populateTable($table, data);
            });
        });
    })(jQuery);
</script>